# Generated by Django 3.2.9 on 2022-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('mobile', models.CharField(max_length=12)),
                ('eventDate', models.DateTimeField()),
            ],
        ),
    ]
