# Generated by Django 3.2.9 on 2022-03-29 21:33

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='eventDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(default=blogs.models.create_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
